
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.USFDEnterprise;
import Business.Organization.CustomerOrganization;
import Business.ProduceReview.ProduceReview;
import Business.ProduceReview.ProduceReviewDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProduceRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Mohandas
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerOrganization organization;
    private UserAccount userAccount;
    private USFDEnterprise enterprise;
    private ProduceReviewDirectory prDirectory;
     private ButtonGroup qualitybg = new ButtonGroup();
    private ButtonGroup shelfbg = new ButtonGroup();
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CustomerOrganization organization, Enterprise enterprise,ProduceReviewDirectory prDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = (USFDEnterprise)enterprise;
        this.userAccount = account;
        this.prDirectory = prDirectory;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
        qualitygroupbutton();
         shelfgroupbutton();
        //checkCompletion();
    }
     private void qualitygroupbutton() {
        qualitybg.add(qexRadioButton);
        qualitybg.add(qvgRadioButton);
        qualitybg.add(qgRadioButton);
        qualitybg.add(qaRadioButton);
        qualitybg.add(qpRadioButton);
    }
    
     private void shelfgroupbutton() {
        shelfbg.add(sleRadioButton);
        shelfbg.add(svgRadioButton);
        shelfbg.add(sgRadioButton);
        shelfbg.add(saRadioButton);
        shelfbg.add(spRadioButton);
    }

    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            row[3] = request.getCropQty();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        additionalreviewsTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qexRadioButton = new javax.swing.JRadioButton();
        sleRadioButton = new javax.swing.JRadioButton();
        svgRadioButton = new javax.swing.JRadioButton();
        qvgRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        qgRadioButton = new javax.swing.JRadioButton();
        qaRadioButton = new javax.swing.JRadioButton();
        saRadioButton = new javax.swing.JRadioButton();
        sgRadioButton = new javax.swing.JRadioButton();
        spRadioButton = new javax.swing.JRadioButton();
        qpRadioButton = new javax.swing.JRadioButton();
        reviewButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Crop Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 206, 620, 165));

        requestTestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestTestJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crop-icon (1).png"))); // NOI18N
        requestTestJButton.setText("Request Crop");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 196, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 141, 127, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 141, 158, 26));

        additionalreviewsTextArea.setColumns(20);
        additionalreviewsTextArea.setRows(5);
        additionalreviewsTextArea.setEnabled(false);
        jScrollPane2.setViewportView(additionalreviewsTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 622, 507, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Additional Reviews");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 622, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Produce Shelf Life");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 550, 147, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Produce Quality");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 501, 147, -1));

        qexRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qexRadioButton.setText("Excellent");
        qexRadioButton.setEnabled(false);
        add(qexRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 497, -1, -1));

        sleRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sleRadioButton.setText("Excellent");
        sleRadioButton.setEnabled(false);
        add(sleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 546, -1, -1));

        svgRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        svgRadioButton.setText("Very Good");
        svgRadioButton.setEnabled(false);
        add(svgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 546, -1, -1));

        qvgRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qvgRadioButton.setText("Very Good");
        qvgRadioButton.setEnabled(false);
        qvgRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qvgRadioButtonActionPerformed(evt);
            }
        });
        add(qvgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 497, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-comments-icon (1).png"))); // NOI18N
        jLabel1.setText("Review Crop");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 447, 198, -1));

        qgRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qgRadioButton.setText("Good");
        qgRadioButton.setEnabled(false);
        add(qgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 497, -1, -1));

        qaRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qaRadioButton.setText("Average");
        qaRadioButton.setEnabled(false);
        add(qaRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 497, -1, -1));

        saRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saRadioButton.setText("Average");
        saRadioButton.setEnabled(false);
        add(saRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 546, -1, -1));

        sgRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sgRadioButton.setText("Good");
        sgRadioButton.setEnabled(false);
        add(sgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 546, -1, -1));

        spRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spRadioButton.setText("Poor");
        spRadioButton.setEnabled(false);
        add(spRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 546, -1, -1));

        qpRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qpRadioButton.setText("Poor");
        qpRadioButton.setEnabled(false);
        add(qpRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 497, -1, -1));

        reviewButton.setBackground(new java.awt.Color(255, 153, 102));
        reviewButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reviewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/review icon.png"))); // NOI18N
        reviewButton.setText("Review Crop");
        reviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewButtonActionPerformed(evt);
            }
        });
        add(reviewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 378, 205, -1));

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 736, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.png"))); // NOI18N
        jLabel5.setText("Customer ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 32, 334, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void checkCompletion() {
    int temp = workRequestJTable.getRowCount();
    final String cropName = workRequestJTable.getModel().getValueAt(temp, 0).toString();
    String finalStatus = workRequestJTable.getModel().getValueAt(temp, 2).toString();
    final int quantity = Integer.parseInt((String.valueOf(workRequestJTable.getModel().getValueAt(temp, 4))));
    if(finalStatus.equalsIgnoreCase("Request fulfilled")){
        int delay = 2000; //milliseconds
            ActionListener taskPerformer = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                JOptionPane.showMessageDialog(null, "The request for " +cropName+ " of quantity " +quantity+ " has been successfully delivered!");      
                }
  };
                Timer myTimer = new Timer(delay, taskPerformer);
                myTimer.setRepeats(false);
                myTimer.start();
      
    }
    }
    
    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestProduceJPanel", new RequestProduceJPanel(userProcessContainer, userAccount, enterprise));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void qvgRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qvgRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qvgRadioButtonActionPerformed

    private void reviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
       
       String status = workRequestJTable.getValueAt(selectedRow, 2).toString();
       
       if(status.equalsIgnoreCase("Request fulfilled") || status.equalsIgnoreCase("Completed") || status.equalsIgnoreCase("done")){
            qexRadioButton.setEnabled(true);
            qvgRadioButton.setEnabled(true);
            qgRadioButton.setEnabled(true);
            qaRadioButton.setEnabled(true);
            qpRadioButton.setEnabled(true);

            sleRadioButton.setEnabled(true);
            svgRadioButton.setEnabled(true);
            sgRadioButton.setEnabled(true);
            saRadioButton.setEnabled(true);
            spRadioButton.setEnabled(true);
            
            additionalreviewsTextArea.setEnabled(true);
        
       }
       else{
           JOptionPane.showMessageDialog(null, "Request not fulfilled");
       }
   
    }//GEN-LAST:event_reviewButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        else{
             String status = workRequestJTable.getValueAt(selectedRow, 2).toString();
       String cropName = workRequestJTable.getValueAt(selectedRow, 0).toString();
       String farmerName = workRequestJTable.getValueAt(selectedRow, 1).toString();
        if(status.equalsIgnoreCase("Request fulfilled") || status.equalsIgnoreCase("Completed") || status.equalsIgnoreCase("done") ){
        ProduceReview pr = prDirectory.addProduceReview();
        pr.setCropName(cropName);
        pr.setFarmerName(farmerName);
        
        String quality = null;
        if(qexRadioButton.isSelected())
        quality = "Excellent";
        else if (qvgRadioButton.isSelected())
        quality = "Very Good";
        else if (qgRadioButton.isSelected())
        quality = "Good";
        else if (qaRadioButton.isSelected())
        quality = "Average";
        else if(qpRadioButton.isSelected())
        quality = "Poor";

        

        String shelfLife = null;
        
        if(sleRadioButton.isSelected())
        shelfLife = "Excellent";
        else if (svgRadioButton.isSelected())
        shelfLife = "Very Good";
        else if (sgRadioButton.isSelected())
        shelfLife = "Good";
        else if (saRadioButton.isSelected())
        shelfLife = "Average";
        else if(spRadioButton.isSelected())
        shelfLife = "Poor";
        if (shelfLife == null && quality == null)
        {
            JOptionPane.showMessageDialog(null,"Some field are missing");
        }
        else
        {
        pr.setProduceQuality(quality);
        pr.setProduceShelfLife(shelfLife);
        pr.setAdditionalReviews(additionalreviewsTextArea.getText());
        }
        }
       
        qexRadioButton.setEnabled(false);
            qvgRadioButton.setEnabled(false);
            qgRadioButton.setEnabled(false);
            qaRadioButton.setEnabled(false);
            qpRadioButton.setEnabled(false);

            sleRadioButton.setEnabled(false);
            svgRadioButton.setEnabled(false);
            sgRadioButton.setEnabled(false);
            saRadioButton.setEnabled(false);
            spRadioButton.setEnabled(false);
            
            additionalreviewsTextArea.setEnabled(false);
        }    
            qualitybg.clearSelection();
            shelfbg.clearSelection();
           
            additionalreviewsTextArea.setText(" ");
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea additionalreviewsTextArea;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton qaRadioButton;
    private javax.swing.JRadioButton qexRadioButton;
    private javax.swing.JRadioButton qgRadioButton;
    private javax.swing.JRadioButton qpRadioButton;
    private javax.swing.JRadioButton qvgRadioButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton reviewButton;
    private javax.swing.JRadioButton saRadioButton;
    private javax.swing.JRadioButton sgRadioButton;
    private javax.swing.JRadioButton sleRadioButton;
    private javax.swing.JRadioButton spRadioButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton svgRadioButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
